apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name :  panarik-cluster
  region: eu-central-1

# в каких подсетях будет создан кластер
#vpc:
#  subnets:
#    private: 
#      eu-central-1a: {id: subnet-<SUBNET_ID>}
#      eu-central-1b: {id: subnet-<SUBNET_ID>}
#      eu-central-1c: {id: subnet-<SUBNET_ID>}

nodeGroups:
  - name : worker-nodes-group-1
    instanceType : m5.large
    desiredCapacity : 2
  - name : worker-nodes-group-2
    instanceType : r5.large
    desiredCapacity : 2
